/* Generated By:JJTree: Do not edit this line. ASTAndPredicate.java */

package com.biswa.ep.util.parser.predicate;

public class ASTAndPredicate extends SimpleNode {
  public ASTAndPredicate(int id) {
    super(id);
  }

  public ASTAndPredicate(PredicateBuilder p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PredicateBuilderVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
