/* Generated By:JJTree: Do not edit this line. ASTAttributeOperand.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=com.biswa.ep.util.parser.predicate.impl.CustomNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.biswa.ep.util.parser.predicate;

public
class ASTAttributeOperand extends SimpleNode {
  public ASTAttributeOperand(int id) {
    super(id);
  }

  public ASTAttributeOperand(PredicateBuilder p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PredicateBuilderVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=db0366d3d50252ad4447ea83d9ed9364 (do not edit this line) */
