/* Generated By:JJTree: Do not edit this line. ASTEndPoint.java */

package com.biswa.ep.util.parser.predicate;

public class ASTEndPoint extends SimpleNode {
  public ASTEndPoint(int id) {
    super(id);
  }

  public ASTEndPoint(PredicateBuilder p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PredicateBuilderVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
