/* Generated By:JJTree: Do not edit this line. ASTEmptyPredicate.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=com.biswa.ep.util.parser.predicate.impl.CustomNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.biswa.ep.util.parser.predicate;

public
class ASTEmptyPredicate extends SimpleNode {
  public ASTEmptyPredicate(int id) {
    super(id);
  }

  public ASTEmptyPredicate(PredicateBuilder p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PredicateBuilderVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e2bd52b27ca9243c9d2c99fec7267a92 (do not edit this line) */
