/* Generated By:JJTree: Do not edit this line. ASTOrPredicate.java */

package com.biswa.ep.util.parser.predicate;

public class ASTOrPredicate extends SimpleNode {
  public ASTOrPredicate(int id) {
    super(id);
  }

  public ASTOrPredicate(PredicateBuilder p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PredicateBuilderVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
