/* Generated By:JJTree: Do not edit this line. ASTSOperand.java */

package com.biswa.ep.util.parser.predicate;

public class ASTSOperand extends SimpleNode {
  public ASTSOperand(int id) {
    super(id);
  }

  public ASTSOperand(PredicateBuilder p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PredicateBuilderVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
