/* Generated By:JavaCC: Do not edit this line. PredicateBuilderTreeConstants.java Version 5.0 */
package com.biswa.ep.util.parser.predicate;

public interface PredicateBuilderTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTORPREDICATE = 2;
  public int JJTANDPREDICATE = 3;
  public int JJTSIMPLEPREDICATE = 4;
  public int JJTENDPOINT = 5;
  public int JJTATTRIBUTE = 6;
  public int JJTATTRIBUTEOPERAND = 7;
  public int JJTOPERAND = 8;
  public int JJTSOPERAND = 9;
  public int JJTDOPERAND = 10;
  public int JJTTRUEPREDICATE = 11;
  public int JJTEMPTYPREDICATE = 12;
  public int JJTFALSEPREDICATE = 13;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "OrPredicate",
    "AndPredicate",
    "SimplePredicate",
    "EndPoint",
    "Attribute",
    "AttributeOperand",
    "Operand",
    "SOperand",
    "DOperand",
    "TruePredicate",
    "EmptyPredicate",
    "FalsePredicate",
  };
}
/* JavaCC - OriginalChecksum=2a8aa5cb6efb06e3973b3f585c6da370 (do not edit this line) */
