/* Generated By:JJTree: Do not edit this line. ASTFalsePredicate.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=com.biswa.ep.util.parser.predicate.impl.CustomNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.biswa.ep.util.parser.predicate;

public
class ASTFalsePredicate extends SimpleNode {
  public ASTFalsePredicate(int id) {
    super(id);
  }

  public ASTFalsePredicate(PredicateBuilder p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PredicateBuilderVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=12eee4a2b36220ae0e0c1e3f2e4b94d7 (do not edit this line) */
