/* Generated By:JJTree: Do not edit this line. ASTOperand.java */

package com.biswa.ep.util.parser.predicate;

public class ASTOperand extends SimpleNode {
  public ASTOperand(int id) {
    super(id);
  }

  public ASTOperand(PredicateBuilder p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PredicateBuilderVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
