/* Generated By:JJTree: Do not edit this line. ASTSimplePredicate.java */

package com.biswa.ep.util.parser.predicate;

public class ASTSimplePredicate extends SimpleNode {
  public ASTSimplePredicate(int id) {
    super(id);
  }

  public ASTSimplePredicate(PredicateBuilder p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PredicateBuilderVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
