/* Generated By:JJTree: Do not edit this line. ASTTruePredicate.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=com.biswa.ep.util.parser.predicate.impl.CustomNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.biswa.ep.util.parser.predicate;

public
class ASTTruePredicate extends SimpleNode {
  public ASTTruePredicate(int id) {
    super(id);
  }

  public ASTTruePredicate(PredicateBuilder p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PredicateBuilderVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4b4760b781ff74aeb880cf37f5219d75 (do not edit this line) */
