/* Generated By:JJTree&JavaCC: Do not edit this line. PredicateBuilderConstants.java */
package com.biswa.ep.util.parser.predicate;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PredicateBuilderConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AND = 7;
  /** RegularExpression Id. */
  int OR = 8;
  /** RegularExpression Id. */
  int EQ = 9;
  /** RegularExpression Id. */
  int NE = 10;
  /** RegularExpression Id. */
  int GT = 11;
  /** RegularExpression Id. */
  int LT = 12;
  /** RegularExpression Id. */
  int IN = 13;
  /** RegularExpression Id. */
  int GE = 14;
  /** RegularExpression Id. */
  int LE = 15;
  /** RegularExpression Id. */
  int FALSE = 16;
  /** RegularExpression Id. */
  int TRUE = 17;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 18;
  /** RegularExpression Id. */
  int DECIMAL_PART = 19;
  /** RegularExpression Id. */
  int STRING_LITERAL = 20;
  /** RegularExpression Id. */
  int ATTRIBUTE = 21;
  /** RegularExpression Id. */
  int LETTER = 22;
  /** RegularExpression Id. */
  int DIGIT = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"&&\"",
    "\"||\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\"in\"",
    "\">=\"",
    "\"<=\"",
    "\"false\"",
    "\"true\"",
    "<DECIMAL_LITERAL>",
    "<DECIMAL_PART>",
    "<STRING_LITERAL>",
    "<ATTRIBUTE>",
    "<LETTER>",
    "<DIGIT>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"${\"",
    "\"}\"",
  };

}
