/* Generated By:JavaCC: Do not edit this line. PredicateBuilderVisitor.java Version 5.0 */
package com.biswa.ep.util.parser.predicate;

public interface PredicateBuilderVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTOrPredicate node, Object data);
  public Object visit(ASTAndPredicate node, Object data);
  public Object visit(ASTSimplePredicate node, Object data);
  public Object visit(ASTEndPoint node, Object data);
  public Object visit(ASTAttribute node, Object data);
  public Object visit(ASTAttributeOperand node, Object data);
  public Object visit(ASTOperand node, Object data);
  public Object visit(ASTSOperand node, Object data);
  public Object visit(ASTDOperand node, Object data);
  public Object visit(ASTTruePredicate node, Object data);
  public Object visit(ASTEmptyPredicate node, Object data);
  public Object visit(ASTFalsePredicate node, Object data);
}
/* JavaCC - OriginalChecksum=d07f98e5c020baf287526993efb2c678 (do not edit this line) */
